#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "1.109.2~ynh2"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://immich.app"
admindoc = "https://github.com/immich-app/immich#getting-started"
userdoc = "https://github.com/immich-app/immich#getting-started"
code = "https://github.com/immich-app/immich"

[integration]
yunohost = ">= 11.2"
architectures = ["arm64", "amd64"]
multi_instance = false

ldap = false
sso = false

disk = "2G"
ram.build = "800M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/immich-app/immich/archive/refs/tags/v1.109.2.tar.gz"
        sha256 = "c45bed3fa510d51df6e31e7bbf06bda3413aa4ef751d9c6d7596ffc49b921459"

        autoupdate.strategy = "latest_github_release"

    [resources.ports]
    main.default = 3001
    machinelearning.default = 3003

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.allowed= "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = [
        "python3-venv",
        "python3-dev",
        "ffmpeg",
        "postgresql",
        "wget",
        "build-essential",
        "libreadline-dev",
        "libncursesw5-dev",
        "libssl-dev",
        "libsqlite3-dev",
        "tk-dev",
        "libgdbm-dev",
        "libc6-dev",
        "libbz2-dev",
        "libffi-dev",
        "zlib1g-dev",
        "unzip",
        "uuid-runtime",
        "autoconf",
        "jq",
        "perl",
        "libnet-ssleay-perl",
        "libio-socket-ssl-perl",
        "libcapture-tiny-perl",
        "libfile-which-perl",
        "libfile-chdir-perl",
        "libpkgconfig-perl",
        "libffi-checklib-perl",
        "libtest-warnings-perl",
        "libtest-fatal-perl",
        "libtest-needs-perl",
        "libtest2-suite-perl",
        "libsort-versions-perl",
        "libpath-tiny-perl",
        "libtry-tiny-perl",
        "libterm-table-perl",
        "libany-uri-escape-perl",
        "libmojolicious-perl",
        "libfile-slurper-perl",
        "liblcms2-2"
    ]

    [resources.apt.extras.postgresql]
    repo = "deb https://apt.postgresql.org/pub/repos/apt __YNH_DEBIAN_VERSION__-pgdg main 16"
    key = "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    packages = [
        "libllvm13", "libpq5", "libpq-dev" , "postgresql-16", "postgresql-16-pgvector", "postgresql-client-16", "postgresql-common", "postgresql-client-common"
    ]

    [resources.database]
    type = "postgresql"
